FROM node:alpine as builder

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .
RUN ls -la
RUN npx remix vite:build

# Stage 2: Setup the production environment
FROM node:alpine

WORKDIR /app

# Copy only necessary directories and files
COPY --from=builder /app/build ./build
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/public ./public

CMD ["npx", "remix-serve", "build/server/index.js"]
EXPOSE 3000
